### ISSUE TITLE
Make `CompactSolutionResults`default?

### ISSUE THREAD

**Issue by glwagner** [CliMA/RootSolvers.jl#46]
The "compact" form of the solution might merely be a tuple return value:

https://github.com/CliMA/RootSolvers.jl/blob/ae34ffb4ae5bf8e66b38ef4d8ef385a146302344/src/RootSolvers.jl#L138C1-L138C1

which would save boiler plate in typical user code that embeds `find_zero` in GPU kernels:

```julia
possible_root, converged = find_zero(f, method, solution_type)
```

I also think it'd be reasonable to make this default so we can omit the third argument above, making dependent code even more concise.

**Comment by charleskawczynski** [comment]
Yeah, that might be nice, but one advantage of the struct is that we can dump additional things into there without breaking the API (coincidentally, I may need to do this soon).

**Comment by charleskawczynski** [comment]
I guess either way isn't too big of a deal, though, IMO

**Comment by glwagner** [comment]
That's a fair point. What about making it default?

**Comment by glwagner** [comment]
Not currently, but it's a trivial change:

https://github.com/CliMA/RootSolvers.jl/blob/ae34ffb4ae5bf8e66b38ef4d8ef385a146302344/src/RootSolvers.jl#L270-L275
